[package]
name = "tauri-specta"
description = "Completely typesafe Tauri commands"
version = "2.0.0-rc.11"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/README.md", "/LICENCE"]
repository = "https://github.com/oscartbeaumont/tauri-specta"
documentation = "https://docs.rs/tauri-specta/latest/tauri-specta"
keywords = ["async", "specta", "rspc", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

# /bin/sh RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --all-features
[package.metadata."docs.rs"]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
javascript = ["specta/typescript", "specta/js_doc"]
typescript = ["specta/typescript", "specta/js_doc"]

[dependencies]
# Public
specta = { git = "https://github.com/jsimonrichard/specta", features = [
    "function",
] }
tauri-specta-macros = { version = "=2.0.0-rc.5", path = "./macros" }
serde = "1"
serde_json = "1"
thiserror = "1"
tauri = { git = "https://github.com/jsimonrichard/tauri", branch = "jsimonrichard-dev-specta", no-default-features = true, features = [
    "specta",
] }

# Private
heck = "0.5.0"
indoc = "2.0.5"

[workspace]
members = [
    "examples/app/src-tauri",
    "examples/custom-plugin/app/src-tauri",
    "examples/custom-plugin/plugin",
    "macros",
]
